name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "22.11"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint
        continue-on-error: true
        run: npm run lint

      - name: Format check
        continue-on-error: true
        run: npm run format:check

      - name: Build
        id: build
        continue-on-error: true
        run: npm run build

      - name: Test
        if: steps.build.outcome == 'success'
        run: npm run test
