name: CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [main]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Quality checks
        run: |
          npm run lint
          npm run format:check
          npm run test
          npm run build

      - name: Create PR to main if checks pass
        if: success() && github.ref == 'refs/heads/dev'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          title: 'Automated PR: Dev to Main'
          body: 'All checks passed - ready to merge to main'
